/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Modelos.Usuario;
import javax.swing.JOptionPane;

    private Object txtCantidad;
    private Object txtDestino;
/**
 *
 * @author Dell
 */
    
 
public class FrmBanco extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBanco.class.getName());
    private Usuario usuario;
    private javax.swing.JTextField txtCantidad = new javax.swing.JTextField();
    private javax.swing.JTextField txtDestino = new javax.swing.JTextField();

    public FrmBanco(Usuario usuario) {
        initComponents();
        this.usuario = usuario;

        setLocationRelativeTo(null);
        setTitle("Banco");

        cargarDatosUsuario();;
}
    
    // Metodo para cargar datos
    public void cargarDatosUsuario() {
        lblNombre.setText(usuario.getRol()); 
        lblCorreo.setText(usuario.getCorreo());
        
    }
    //Actualizar Saldo
        public void actualizarSaldo(double saldo) {
        lblSaldo.setText("$ " + saldo);
        } 
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblNumeroCuenta = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblDeuda = new javax.swing.JLabel();
        btnRetirar = new javax.swing.JButton();
        btnTranferir = new javax.swing.JButton();
        btnPrestamo = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblCorreo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 82, 90));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Diego Alonso Escalante Gómez");

        lblNumeroCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumeroCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroCuenta.setText("0101010101");

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldo.setText("Saldo Actual");

        lblDeuda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDeuda.setForeground(new java.awt.Color(255, 255, 255));
        lblDeuda.setText("Deuda Actual");

        btnRetirar.setBackground(new java.awt.Color(153, 153, 153));
        btnRetirar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(this::btnRetirarActionPerformed);

        btnTranferir.setBackground(new java.awt.Color(153, 153, 153));
        btnTranferir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTranferir.setText("Transferir");
        btnTranferir.addActionListener(this::btnTranferirActionPerformed);

        btnPrestamo.setBackground(new java.awt.Color(153, 153, 153));
        btnPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrestamo.setText("Prestamo");
        btnPrestamo.addActionListener(this::btnPrestamoActionPerformed);

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("123456@gmail.com");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(lblDeuda)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNumeroCuenta)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnRetirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion)
                    .addComponent(btnTranferir))
                .addGap(44, 44, 44)
                .addComponent(btnPrestamo)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCorreo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumeroCuenta)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo)
                    .addComponent(lblDeuda))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirar)
                    .addComponent(btnTranferir)
                    .addComponent(btnPrestamo))
                .addGap(32, 32, 32)
                .addComponent(btnCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lblCorreo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
try {
            double cantidad = Double.parseDouble(txtCantidad.getText());
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "Cantidad inválida");
                return;
            }
            JOptionPane.showMessageDialog(this, "Retiro simulado: $" + cantidad);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingresa un número válido");
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnTranferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranferirActionPerformed
       try {
            double cantidad = Double.parseDouble(txtCantidad.getText());
            String destino = txtDestino.getText();
            JOptionPane.showMessageDialog(this, "Transferencia a " + destino + " por $" + cantidad);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en datos");
        }
    }//GEN-LAST:event_btnTranferirActionPerformed

    private void btnPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoActionPerformed
       try {
            double cantidad = Double.parseDouble(txtCantidad.getText());
            JOptionPane.showMessageDialog(this, "Préstamo aprobado por $" + cantidad);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en datos");
        }
    }//GEN-LAST:event_btnPrestamoActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnPrestamo;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnTranferir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDeuda;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroCuenta;
    private javax.swing.JLabel lblSaldo;
    // End of variables declaration//GEN-END:variables

}
